### ISSUE TITLE
Looking for hints on how to fix errors

### ISSUE THREAD

**Issue by jedunn** [SjoerdV/ConvertOneNote2MarkDown#13]
I'm a novice with powershell and the errors returned by this script. Do you have any hints on how to troubleshoot the following errors:

![image](https://user-images.githubusercontent.com/15387944/88600806-033dc000-d024-11ea-96cf-d6dd1ae65912.png)

**Comment by SjoerdV** [comment]
Hi @jedunn, thanks for your question. Based on the errors it seems you don’t have OneNote 2016 installed. Please check the guidance and especially the prerequisites in the readme again and you can also search closed issues for things you might encounter.

**Comment by jedunn** [comment]
I may have been running things in the wrong environment. Once the script was opened and run in PowerShell ISE OneNote was able to launch and script ran successfully. Thanks for your help and the script!
