### ISSUE TITLE
Replace absolute path of images by relative path

### ISSUE THREAD

**Issue by dirkagterhuis** [SjoerdV/ConvertOneNote2MarkDown#2]
So, I've successfully converted all my Onenote notebooks to markdown, thanks for that! You saved me a tremendous amount of work. 

I've moved all notes from the directory I initially put the markdown files to another directory, and noticed that images stopped working because the path referenced is absolute, e.g. 'D:/User/MyNotes/media/...'. I replaced this with the relative path of './media/...' to have them all work again. 

I think this can be fixed somewhere around line 181 of the .ps1 file. I attempted a pull request, but I don't know enough of Powershell to replace the part of variable 'fullexportpathwithoutextension' so it just contains './media/<image name>. 

This would have the script convert Onenote to markdown and lets you then move the notes around as you please!

**Comment by SjoerdV** [comment]
Hi Dirk, thanks for your continued feedback. As pandoc didn’t really work that well with relative paths I decided to keep the full target path leading throughout the script. What you do after script execution is all up to the user. Therefore I will not be making your suggested alteration here, but you are free to fork the project, of course.
