### ISSUE TITLE
subpages with identical names but in different parents overwrite each other

### ISSUE THREAD

**Issue by FrankEppink** [SjoerdV/ConvertOneNote2MarkDown#23]
# Problem
OneNote subpages are not correctly handled in the scenario with two subpages with the same name but belonging to different parents. The created word documents have the same name, hence the latter one overwrites the earlier one.

## Example

- Parentpage01
    - SubpageA
- Parentpage02
    - SubpageA

This will result in a single **SubpageA.docx** word document, where the latter one has overwritten the earlier one.

# Fix
I think the bug would be fixed by adding the second statement

```
$fullexportpathwithoutextension = "$($fullexportdirpath)\$($pagename)"
$fullexportpath = "$($fullexportpathwithoutextension).docx"
```
after https://github.com/SjoerdV/ConvertOneNote2MarkDown/blob/master/ConvertOneNote2MarkDown.ps1#L118

so that the line
> $OneNote.Publish($pageid, $fullexportpath, "pfWord", "")

in https://github.com/SjoerdV/ConvertOneNote2MarkDown/blob/master/ConvertOneNote2MarkDown.ps1#L122

actually uses the correct and unique name including the pagename.

also the earlier check in 
https://github.com/SjoerdV/ConvertOneNote2MarkDown/blob/master/ConvertOneNote2MarkDown.ps1#L65
should be moved lower into line 120 to check the actual word file path.

**Comment by SjoerdV** [comment]
@FrankEppink you were absolutely right. Corrected the script to your recommendations. Thanks a lot for making this somewhat better. If you agree with the commit please close the issue.
