### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by edugodoyo** [SjoerdV/ConvertOneNote2MarkDown#24]
I've followed the instructions but when running the script I[ve got an error (below).
Windows 10 Version = 20H2 Build 19042.1288
OneNote version = 1808 (Msft office Professional Plus 2019)
Pandoc Version = 2.16.2

Error:

-New-Object : Retrieving the COM class factory for component with CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E} failed
due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005
(CO_E_SERVER_EXEC_FAILURE)).
At C:\Users\edugoliv\Downloads\ConvertOneNote2MarkDown.ps1:18 char:14
+   $OneNote = New-Object -ComObject OneNote.Application
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Users\edugoliv\Downloads\ConvertOneNote2MarkDown.ps1:21 char:3
+   $OneNote.GetHierarchy("", [Microsoft.Office.InterOp.OneNote.Hierarc ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Users\edugoliv\Downloads\ConvertOneNote2MarkDown.ps1:219 char:3
+   [System.Runtime.Interopservices.Marshal]::ReleaseComObject($OneNote ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Remove-Variable : Cannot find a variable with the name 'OneNote'.
At C:\Users\edugoliv\Downloads\ConvertOneNote2MarkDown.ps1:220 char:3
+   Remove-Variable OneNote
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OneNote:String) [Remove-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand

**Comment by SjoerdV** [comment]
Please see #11
