### ISSUE TITLE
`ConvertOneNote2MarkDown.ps1` exits after taking path, doesn't convert anything

### ISSUE THREAD

**Issue by Saad-Mufti** [SjoerdV/ConvertOneNote2MarkDown#25]
I ran the script, entered in an absolute path that exists, and I briefly saw one of my notebook's names on the terminal window before it closed. I checked the folder to find that only one empty folder was created. What exactly happened?

On a related note, I think it would be very useful to include error messages in the script to better help the user understand why it might have failed, rather than simply exiting immediately.

**Comment by SjoerdV** [comment]
1. Just to be sure: Please run the script in an already opened PowerShell terminal, not by double clicking the script 
2. Please read all the [instructions](https://github.com/SjoerdV/ConvertOneNote2MarkDown#readme)
3. scan for existing [issues](https://github.com/SjoerdV/ConvertOneNote2MarkDown/issues) 

I hope you can make it work for you! 

Closing this issue in **one week** on no further activity
