### ISSUE TITLE
Script at present seems to need powershell 6 or below.  

### ISSUE THREAD

**Issue by lenusmars** [SjoerdV/ConvertOneNote2MarkDown#26]
Just as a note the script seems to fail with any version of Powershell 7

**Comment by SjoerdV** [comment]
That's a correct observation!

Seeing that all kinds of legacy Com/Interop stuff is going on using a 2013 product stack, your best bet is to query the OneNote part of the Microsoft Graph for future 'notebook export' endeavors.

This repo is still valid for people who have a Windows 7/10, Windows PowerShell 5.1 and OneNote 2016 combo in place btw.

My intention is to close this issue with a label 'wontfix' if you don't mind.

**Comment by SjoerdV** [comment]
I will update the Readme btw. The initial commit dates from just before the PS7 GA date (which was december 2019). 

So it makes sense.

**Comment by lenusmars** [comment]
Don't mind at all,   Great script!  Just wanted to save people from my own foolishness.
