### ISSUE TITLE
Instructions for Installing from Chocolatey

### ISSUE THREAD

**Issue by nixsee** [SjoerdV/ConvertOneNote2MarkDown#7]
Hi there, thanks for making this. I installed Chocolately using the instructions in the page you linked to. But I don't know how to install this script using it - I can't find it in their listed packages. Could you write some quick instructions for how to do so? Thanks!

**Comment by nixsee** [comment]
Oh - I see what's going on. The tip was to install Pandoc from choco. I only noticed that as a requirement after running the script filled with errors regarding Pandoc.

Also, as JohnKyle4 mentions [here](https://github.com/SjoerdV/ConvertOneNote2MarkDown/issues/4), OneNote needs to be opened in Administrator mode. Looks like it's working, along with the tips you gave there for trimming long titles!

**Comment by SjoerdV** [comment]
Hi @nixsee glad to see you sorted it out
